name: yapefalso
description: "A project to replicate yape for practice purporse."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_riverpod: 
  riverpod_annotation: 
  camera: 0.11.0
  google_mlkit_barcode_scanning: ^0.13.0
  sliver_tools: ^0.2.12
  camera_android: ^0.10.9+14
  auto_route: ^9.2.2
  supabase_flutter: ^2.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: 
  riverpod_lint:
  custom_lint:  
  auto_route_generator:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
