name: yapefalso
description: "A project to replicate yape for practice purporse."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_riverpod: 
  riverpod_annotation: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: 
  riverpod_lint:
  custom_lint:  
  build_runner:

flutter:
  uses-material-design: true
