name: yapefalso
description: "A project to replicate yape for practice purporse."
publish_to: 'none'
version: 1.6.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_riverpod: 
  riverpod_annotation: 
  camera: 0.11.0
  google_mlkit_barcode_scanning: ^0.13.0
  sliver_tools: ^0.2.12
  camera_android: ^0.10.9+14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: 
  riverpod_lint:
  custom_lint:  
  build_runner:

flutter:
  uses-material-design: true
